### ISSUE TITLE
Using a method inside where

### ISSUE THREAD

**Issue by sic2** [my2iu/Jinq#37]
Hello,

I am trying to have methods inside my where statement. Here is a simplified example:

```
Collection<ExperimentLog> experimentLogs = experiments(entityManager)
               .where(log -> test(log.getGroupid(), groupid))
                .sortedDescendingBy(log -> log.getSubmittime())
                .limit(20)
                .toList();
```

And my test method looks like this one:

```
private boolean test(int test, int groupid) {
        return test == groupid;
    }
```
However, I get the following error:
```
java.lang.IllegalArgumentException: Lambda has an unknown format (an unsupported type of method handle is possibly being used here)
	at org.jinq.jpa.transform.LambdaAnalysis.fullyAnalyzeLambda(LambdaAnalysis.java:176)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

My understanding of streams and lambda in java 8 is very limited. I would appreciate any help.
Thanks!

**Comment by my2iu** [comment]
Jinq does not support the use of custom methods inside its queries. It only supports some limited methods that it knows how to translate into database queries such as those listed in the Jinq Query Guide:

http://www.jinq.org/docs/queries.html#N66066

**Comment by sic2** [comment]
Thank you @my2iu . I guess I will just use multiple functions returning new JinqStreams then.
