### ISSUE TITLE
Java 10 support

### ISSUE THREAD

**Issue by nghexuanchien** [my2iu/Jinq#71]
I tried using JDK 10 with ASM 6.1.1, the query is broken

> Caused by: java.lang.IllegalArgumentException: Could not translate code to a query
        at jinq.jpa@1.8.23/org.jinq.jpa.JPAQueryComposer.translationFail(JPAQueryComposer.java:113)
        at jinq.jpa@1.8.23/org.jinq.jpa.JPAQueryComposer.applyTransformWithLambda(JPAQueryComposer.java:300)
        at jinq.jpa@1.8.23/org.jinq.jpa.JPAQueryComposer.where(JPAQueryComposer.java:449)
        at jinq.jpa@1.8.23/org.jinq.jpa.JPAQueryComposer.where(JPAQueryComposer.java:63)
        at api@1.8.23/org.jinq.orm.stream.QueryJinqStream.where(QueryJinqStream.java:45)
        at jinq.jpa@1.8.23/org.jinq.jpa.QueryJPAJinqStream.where(QueryJPAJinqStream.java:106)
        at jinq.jpa@1.8.23/org.jinq.jpa.QueryJPAJinqStream.where(QueryJPAJinqStream.java:15)
        at com.retailshop.db.dao.impl.OrderDAO.findByStatus(OrderDAO.java:63)
        at com.retailshop.db.dao.impl.OrderDAO.findRecentSaleOrders(OrderDAO.java:37)
        at com.retailshop.db.dao.impl.OrderDAO.findRecentSaleOrders(OrderDAO.java:32)
        at com.retailshop.db.dao.impl.OrderDAO$$FastClassBySpringCGLIB$$837986ae.invoke(<generated>)
        at spring.core@5.0.5.RELEASE/org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at spring.aop@5.0.5.RELEASE/org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
        at spring.aop@5.0.5.RELEASE/org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at spring.tx@5.0.5.RELEASE/org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        ... 70 more

**Comment by my2iu** [comment]
Version 1.8.24 with ASM 6.1.1 is now available for download from Maven Central.

**Comment by nghexuanchien** [comment]
I tried with 1.8.24 and it worked like a charm now. Thank you so much
