### ISSUE TITLE
Does not work with Java 8 method references

### ISSUE THREAD

**Issue by mkotsbak** [my2iu/Jinq#9]
I tried changing this line in the sample from

.sortedDescendingBy(c -> c.getSalary()

to 

.sortedDescendingBy(Customer::getSalary)

and then it fails:

Exception in thread "main" java.lang.IllegalArgumentException: Could not translate code to a query
	at org.jinq.jpa.JPAQueryComposer.translationFail(JPAQueryComposer.java:113)
	at org.jinq.jpa.JPAQueryComposer.applyTransformWithLambda(JPAQueryComposer.java:285)
	at org.jinq.jpa.JPAQueryComposer.sortedBy(JPAQueryComposer.java:377)
	at org.jinq.jpa.JPAQueryComposer.sortedBy(JPAQueryComposer.java:58)
	at org.jinq.orm.stream.QueryJinqStream.sortedDescendingBy(QueryJinqStream.java:247)
	at org.jinq.jpa.QueryJPAJinqStream.sortedDescendingBy(QueryJPAJinqStream.java:215)
	at org.jinq.jpa.QueryJPAJinqStream.sortedDescendingBy(QueryJPAJinqStream.java:12)
	at SampleMain.runSampleQueries(SampleMain.java:168)
	at SampleMain.main(SampleMain.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.jinq.jpa.transform.QueryTransformException: ch.epfl.labos.iu.orm.queryll2.symbolic.TypedValueVisitorException: Unhandled symbolic execution operation: (this.salary)
	at org.jinq.jpa.transform.SortingTransform.apply(SortingTransform.java:41)
	at org.jinq.jpa.JPAQueryComposer.applyTransformWithLambda(JPAQueryComposer.java:281)
	... 12 more
Caused by: ch.epfl.labos.iu.orm.queryll2.symbolic.TypedValueVisitorException: Unhandled symbolic execution operation: (this.salary)
	at org.jinq.jpa.transform.SymbExToColumns.defaultValue(SymbExToColumns.java:52)
	at org.jinq.jpa.transform.SymbExToColumns.defaultValue(SymbExToColumns.java:39)
	at ch.epfl.labos.iu.orm.queryll2.symbolic.TypedValueVisitor.unaryOpValue(TypedValueVisitor.java:82)
	at ch.epfl.labos.iu.orm.queryll2.symbolic.TypedValueVisitor.getFieldValue(TypedValueVisitor.java:98)
	at ch.epfl.labos.iu.orm.queryll2.symbolic.TypedValue$GetFieldValue.visit(TypedValue.java:206)
	at org.jinq.jpa.transform.JPQLQueryTransform.simplifyAndTranslatePathToColumns(JPQLQueryTransform.java:110)
	at org.jinq.jpa.transform.JPQLQueryTransform.simplifyAndTranslateMainPathToColumns(JPQLQueryTransform.java:102)
	at org.jinq.jpa.transform.JPQLQueryTransform.makeSelectExpression(JPQLQueryTransform.java:36)
	at org.jinq.jpa.transform.SortingTransform.apply(SortingTransform.java:28)
	... 13 more

**Comment by my2iu** [comment]
It looks like the Java 8 lambda designers were being way too clever again. In Eclipse, everything works fine because the compiler simply compiles method references the obvious way. But it looks like the JDK is doing something funky with the lambda metafactory in its compiled output as an "optimization" or something. It might take me a bit to figure out what's going on there.

**Comment by mkotsbak** [comment]
Ok. If it helps, I used IntelliJ when this happened. Not sure if it used the internal compiler or through Maven.

**Comment by my2iu** [comment]
I've fixed this in the latest 1.8.2 release of Jinq.

**Comment by mkotsbak** [comment]
Thanks for a quick fix and release! It works fine in my actual query code now :)
