### ISSUE TITLE
Could not analyze lambda code

### ISSUE THREAD

**Issue by sysmat** [my2iu/Jinq#91]
* org.jinq:jinq-jpa:1.8.30
* Using Pair

```java
JinqJPAStreamProvider streams = new JinqJPAStreamProvider(factory);
JinqStream<AaiUser> usersStream = streams.streamAll(em, AaiUser.class);
List<Pair<Long, Date>> pairs = usersStream.select(u -> new Pair<>(u.id, u.created)).toList();
```
* I got run time error:
```
Exception in thread "main" java.lang.IllegalArgumentException: Could not analyze lambda code
	at org.jinq.jpa.transform.LambdaAnalysis.fullyAnalyzeLambda(LambdaAnalysis.java:197)
	at org.jinq.jpa.transform.LambdaInfo.fullyAnalyze(LambdaInfo.java:116)
	at org.jinq.jpa.JPAQueryComposer.applyTransformWithLambda(JPAQueryComposer.java:287)
	at org.jinq.jpa.JPAQueryComposer.select(JPAQueryComposer.java:491)
	at org.jinq.jpa.JPAQueryComposer.select(JPAQueryComposer.java:63)
	at org.jinq.orm.stream.QueryJinqStream.select(QueryJinqStream.java:62)
	at org.jinq.jpa.QueryJPAJinqStream.select(QueryJPAJinqStream.java:127)
	at org.jinq.jpa.QueryJPAJinqStream.select(QueryJPAJinqStream.java:15)
	at vid.JinqConn.main(JinqConn.java:32)
Caused by: org.jinq.rebased.org.objectweb.asm.tree.analysis.AnalyzerException: Unhandled field access
	at ch.epfl.labos.iu.orm.queryll2.symbolic.SymbolicInterpreterWithFieldAccess.unaryOperation(SymbolicInterpreterWithFieldAccess.java:58)
	at org.jinq.rebased.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:567)
	at ch.epfl.labos.iu.orm.queryll2.path.CodePath.calculateReturnValueAndConditions(CodePath.java:148)
	at ch.epfl.labos.iu.orm.queryll2.path.TransformationClassAnalyzer.analyzeMethod(TransformationClassAnalyzer.java:510)
	at ch.epfl.labos.iu.orm.queryll2.path.TransformationClassAnalyzer.analyzeLambdaMethod(TransformationClassAnalyzer.java:476)
	at org.jinq.jpa.transform.LambdaAnalysis.analyzeLambda(LambdaAnalysis.java:318)
	at org.jinq.jpa.transform.LambdaAnalysis.fullyAnalyzeLambda(LambdaAnalysis.java:187)
```

**Comment by my2iu** [comment]
Jinq does not support entities that use field access. Jinq only supports using getters.
